vim.g.mapleader = ' '
vim.opt.tabstop = 4
vim.opt.shiftwidth= 4
vim.opt.expandtab = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.signcolumn= 'yes:1'
vim.o.termguicolors = true
vim.g.airline_theme = "tomorrow"
vim.opt.clipboard = 'unnamedplus'
