require("plugin_config.nvim_tree")
require("plugin_config.tree_sitter")
require("plugin_config.go")
--require("plugin_config.hologram")
--require("plugin_config.telescope_config")
--require("plugin_config.project_nvim")
