require("debugger")
require("plugin")
require("colorschema")
require("lsp")
require("completions")
require("config")
require("plugin_config")
require("keymap")
require("neotest_config")

--require("noice-config")
